# Default values for k3s_masters nodes. These can be overridden per node in inventory.yaml
vm_cpu_cores: 3
vm_memory_mb: 6144
vm_disk_gb: 50
vlan_id: 20
network_gateway: "192.168.20.1"
netmask_cidr: 23
# Use an external DNS server (cloudflare) to avoid circular dependencies when running
# DNS servers (Pi-Hole) in k8s
dns_servers:
  - 1.1.1.1
  - 1.0.0.1
